[project]
name = "mcp-sentiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio[mcp]>=5.46.1",
    "jupyter>=1.1.1",
    "textblob>=0.19.0",
]
